#!/bin/sh

# Package
PACKAGE="PythonMiniProbe"
DNAME="prtgprobe"

# Others
INSTALL_DIR="/usr/local/${PACKAGE}"
PYTHON_DIR="/usr/local/python"
TEMP="/tmp"
PATH="${INSTALL_DIR}/bin:${INSTALL_DIR}/env/bin:${PYTHON_DIR}/bin:${PATH}"
CFG_FILE="${INSTALL_DIR}/miniprobe/probe.conf"

SERVICETOOL="/usr/syno/bin/servicetool"

UUID=$(cat /proc/sys/kernel/random/uuid)

VIRTUALENV="${PYTHON_DIR}/bin/virtualenv"

STARTUPSCRIPT=/usr/local/etc/rc.d/PythonMiniProbe.sh


preinst ()
{
	exit 0
}

postinst ()
{
	# Link
	ln -s ${SYNOPKG_PKGDEST} ${INSTALL_DIR}

	# Create a Python virtualenv
    ${VIRTUALENV} --system-site-packages ${INSTALL_DIR}/env > /dev/null

    # Install python modules
    cd ${INSTALL_DIR}
    ${INSTALL_DIR}/env/bin/pip install -r ${INSTALL_DIR}/requirements.txt > /dev/null

	# Create user
	adduser -h ${INSTALL_DIR} -g "${DNAME} User" -G users -s /bin/sh -S -D ${PACKAGE}

	# Correct the files ownership
	chown -R ${PACKAGE}:root ${SYNOPKG_PKGDEST}

    # Edit the configuration according to the wizard
    sed -i -e "s|@name@|${wizard_name}|g" ${CFG_FILE}
	sed -i -e "s|@server@|${wizard_server}|g" ${CFG_FILE}
	sed -i -e "s|@key@|${wizard_key}|g" ${CFG_FILE}
	sed -i -e "s|@port@|${wizard_port}|g" ${CFG_FILE}
	sed -i -e "s|@gid@|${UUID}|g" ${CFG_FILE}

	# Create startup script 
	cp `dirname $0`/start-stop-status ${STARTUPSCRIPT}
	chown ${PACKAGE}:root ${STARTUPSCRIPT}
	chmod 755 ${STARTUPSCRIPT}

	# restore ping
    chmod u-s `which ping`

    # create miniprobe ping
    cp /bin/ping /bin/miniprobeping
    chmod u+s /bin/miniprobeping

	# remove startup script
    rm ${STARTUPSCRIPT}

	exit 0
}

preuninst ()
{
	# Remove the user (if not upgrading)
	if [ "${SYNOPKG_PKG_STATUS}" != "UPGRADE" ]; then
		deluser ${PACKAGE}
	fi

	# restore ping
    chmod u-s `which ping`
    rm /bin/miniprobeping


	exit 0
}

postuninst ()
{
	# Remove link
	rm -f ${INSTALL_DIR}

	# Remove startup script
	rm ${STARTUPSCRIPT}

	exit 0
}

preupgrade ()
{	
    # Save some stuff
    rm -fr ${TEMP}/${PACKAGE}
    mkdir -p ${TEMP}/${PACKAGE}
    cp ${INSTALL_DIR}/miniprobe/probe.conf ${TEMP}/${PACKAGE}/probe.conf

	exit $?
}

postupgrade ()
{
    # Restore some stuff
    cp ${TEMP}/${PACKAGE}/probe.conf ${INSTALL_DIR}/miniprobe/probe.conf
    rm -fr ${TEMP}/${PACKAGE}

	# Correct the files ownership
	chown -R ${PACKAGE}:root ${SYNOPKG_PKGDEST}

	exit 0
}
